### PR TITLE
feat: add PendingTransactions indicator

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

Closes: https://github.com/snapshot-labs/sx-ui/issues/367
Depends on: https://github.com/snapshot-labs/sx-ui/pull/371

This PR changes how pending transaction indicator works:
- It's now part of top nav, it handles both transactions that wait to be broadcast (same as old one) as well as track transactions until confirmation.
- Once txId is received you can browse pending transactions and open them in explorer.
- txIds are persisted.

## Test plan

- Propose/vote.
- Indicator gets increased once you confirm transaction in Metamask.
- You can click on indicator (shows X transactions broadcasting).
- Once response comes back it shows transaction ID and you can open it in explorer.
- Once it gets confirmed it gets removed.

### CODE REVIEW

**Comment by bonustrack** [comment]
The space in red here is too large now:
image

Should be like before:
image

Can you also remove the white border here:
image

**Comment by bonustrack** [comment]
Still seeing the white border for some reason

**Comment by bonustrack** [comment]
- Is it supposed to persist with localStorage? I can't see the pending tx anymore when I refresh the page.
- Can you make the text white for pending count on light mode here:
image

**Comment by Sekhmet** [comment]
> Is it supposed to persist with localStorage? I can't see the pending tx anymore when I refresh the page.

If you wait til transaction receipt is returned then it should. Creating proposal takes 20-30 seconds to receive tx_id, so if you refresh during that window we have no txId to track.

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
