### PR TITLE
feat: add ability to edit proposals

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

Closes: https://github.com/snapshot-labs/sx-ui/issues/562

## Test plan
- Use local mana https://github.com/snapshot-labs/mana/pull/95
- Create proposal with space with some voting delay, for example there http://localhost:8080/#/gor:0x65e4329e8c0fba31883b98e2cf3e81d3cdcac780 you have 4 hours.
- Go to proposal page within 4 hours signed in as proposal author.
- You can edit the proposal (button at the top).
- You can submit the new proposal.
- It gets updated after a while.

### CODE REVIEW

**Comment by bonustrack** [comment]
If I remove a transaction from a proposal execution I got this error:
image

**Comment by Sekhmet** [comment]
@bonustrack is this with local version of Mana? I cannot reproduce with custom Mana.

**Comment by bonustrack** [comment]
My bad, this is with current Mana, will test again

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
