### PR TITLE
fix: Keyboard navigation for buttons

### PR DESCRIPTION
**Pull request by samwhosung**
### Summary

Fixes keyboard navigation for button, before outline was disabled everywhere and now it's just disabled for inputs. Also added some buttons where I found them to be missing.

### CODE REVIEW

**Review by Sekhmet — COMMENTED** [review]
With this PR combined https://github.com/snapshot-labs/sx-ui/pull/867 it won't have hover state for buttons (UiButtons).

Also this doesn't look that good now (just focusing by mouse, not tabbed in):
image

**Comment by samuveth** [comment]
There was no hover state before either :) Do you want me to add one in this PR?

**Comment by samuveth** [comment]
Oh I see, would you prefer we remove the `outline-0` from button or use `focus-visible:border-skin-link` which will only focus when using keyboard?

It would behave consistently with other buttons in the UI if we just remove the `outline-0` so I would go with that.
image

**Comment by samuveth** [comment]
I moved these changed into https://github.com/snapshot-labs/sx-ui/pull/867 for easier testing

**Pull request closed without merging**
