### PR TITLE
feat: add proposals filter

### PR DESCRIPTION
**Pull request by Sekhmet**
Closes: https://github.com/snapshot-labs/sx-ui/issues/687

## Test plan
- Go to http://localhost:8080/#/gor:0xae56be6b3754e5e89de438f6202df07c7aa86845/proposals
- Test different filters

### CODE REVIEW

**Comment by bonustrack** [comment]
Can we use the dropdown component for the filters? We should also remove color bullet for "All", and move "Pending" before "Active".

**Comment by Sekhmet** [comment]
> Can we use the dropdown component for the filters?

I used separate one as Select uses different styles than Dropdown. In current design there were too many differences to unify those, but I mostly guessed how we want it to look like, plain Dropdown didn't look good.

If you have some particular style in mind I can implement that but will need some kind of design as reference.

**Comment by bonustrack** [comment]
What's bug you with dropdown design, I tried locally and to me it's looks good.

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
