### PR TITLE
feat: make executions sortable

### PR DESCRIPTION
**Pull request by Sekhmet**
Closes:  https://github.com/snapshot-labs/sx-ui/issues/184

## Test plan

- Create a new proposal (old drafts might not work because this PR adds unique IDs to executions).
- You can sort them.
- New sort order gets persisted on reload.

## Screenshots

https://user-images.githubusercontent.com/1968722/179423711-864aa58d-f29f-4400-9782-730c92809695.mov

### CODE REVIEW

**Comment by bonustrack** [comment]
Here is my review:
- On mobile it's possible to drag but it's not possible to edit or delete a transaction for me, click don't trigger anything beside sort. We may need on small screen to always show the icons (drag, edit, delete) and make only drag icon activate the sorting. On normal screen we should make icons drag, edit, delete only appear on mouse over
- We shouldn't be able to drag if there is only 1 transaction
- What's the need of "id"? Could we use "nonce" instead? See related issue: https://github.com/snapshot-labs/sx-ui/issues/183

**Comment by bonustrack** [comment]
Please check again my review I made some changes @Sekhmet

**Comment by Sekhmet** [comment]
> What's the need of "id"? Could we use "nonce" instead? See related issue

Mostly for vuedraggable, but it looks like it was possible to workaround it by refactoring how we handle formatting title.

I think I covered all points from review.

**Review by bonustrack — APPROVED** [review]
Looks good

**Pull request merged**
