### PR TITLE
feat: add proposal search

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

Closes: https://github.com/snapshot-labs/sx-ui/issues/507

This PR adds proposal search to space views.

## Test plan

- Go to some space: http://localhost:8080/#/gor:0xcebbae8f9e86f58532837e701650ffdba85738c6
- Search for different strings in proposal strings.

### CODE REVIEW

**Review by bonustrack — COMMENTED** [review]
Looks great, can you just change space between search icon and input to mr-3, and use a font-size of 19px on the input?

Before:
image

After:
image

Also ideally the search icon should use link color (white) when focus on input

**Comment by bonustrack** [comment]
UI is broken on mobile
Screenshot_20230330_161025_Chrome

**Review by bonustrack — APPROVED** [review]
tACK

**Comment by Sekhmet** [comment]
@zzuziak we have added proposal search to Spaces.

**Comment by zzuziak** [comment]
Wdyt about changing the placeholder to `Search proposals`? Currently it looks like a searchbar for everything on the platform

**Pull request merged**
