### PR TITLE
feat(starknet): chore: update to post-audit deployment

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Closes: https://github.com/snapshot-labs/pitches/issues/42

Depends on: https://github.com/snapshot-labs/mana/pull/118
Depends on: https://github.com/snapshot-labs/sx-api/pull/200
Depends on: https://github.com/snapshot-labs/sx.js/pull/227

### How to test

1. Try deploying new space/voting/proposing.
2. You need cairo 1 account to be compatible with StarkSig.

### CODE REVIEW

**Comment by bonustrack** [comment]
I'm able to deploy a space but got some issue with others actions:
- Not able to create a proposal on a space using whitelist as proposal validation and Starknet account, got this error "Input too long for arguments"
- When I try to create a proposal with MetaMask it force me to do a transaction (while this should be just for smart contract wallet)

Did my test with this space:
```sn-tn:0x00710f87a7c48ee1d58fbdcb39b6bb2c821cd592c1f6ea80b5280a909a2c1001/settings```

**Comment by Sekhmet** [comment]
Fixed this issue with EthSig and also some other issue on sx-api, but I have no idea why `Input too long for arguments` happens. It even shows up if I pass no arguments to authenticator 🤔

**Comment by bonustrack** [comment]
I tried to create a space, the tx seem to go through but on the UI it show an error:
image
https://testnet.starkscan.co/tx/0xa3249d02634628d13a23a3af6ea4f3db630e7d83e78afda095a15628c9abdc#overview

**Comment by bonustrack** [comment]
Got it, I also not able to create a proposal, I can see the same issue with Mana it returns "StarknetErrorCode.DEPRECATED_ENDPOINT" error

**Comment by Sekhmet** [comment]
There was missing dependency for starknet.js types that we didn't have installed and deployment failed, should be fine after it's deployed.

**Comment by Sekhmet** [comment]
Tested it now, everything should be working 🤞

**Review by bonustrack — APPROVED** [review]
tACK, space creation, propose and vote works well now

**Pull request merged**
