### PR TITLE
chore: upgrade deps

### PR DESCRIPTION
**Pull request by Sekhmet**
Closes: https://github.com/snapshot-labs/sx-ui/issues/712

`starknet` is not upgraded to satisfy compatibility with sx.js

### CODE REVIEW

**Comment by bonustrack** [comment]
Can we update GitHub action to fix the test?

**Comment by bonustrack** [comment]
We could move choices.json to constants.ts

**Comment by bonustrack** [comment]
So looks like there is also this file that we need to remove:
https://github.com/snapshot-labs/sx-ui/blob/master/src/helpers/execution.json
This may fix the issue with test / build GitHub action

**Comment by Sekhmet** [comment]
We need to update eslint-config.

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
