### PR TITLE
feat: add whitelist support with simplified UI

### PR DESCRIPTION
**Pull request by Sekhmet**
Closes: https://github.com/snapshot-labs/sx-ui/issues/622

This PR adds support for whitelist strategies with simplified UI (textarea where you put addresses in specified format), no custom UI as of now.

## Test plan

- Add Starknet/EVM whitelist strategy to space.
- Try propose/vote.

### CODE REVIEW

**Comment by bonustrack** [comment]
The UI looks good enough that's what I was thinking. I just worry for the usercase where there is like 200k addresses in the whitelist. I don't think that list should be stored in the API directly.

**Comment by bonustrack** [comment]
For the strategy description we can have this:

> A strategy that defines a list of addresses each with designated voting powers, using a Merkle tree for verification of these allocations.

**Comment by Sekhmet** [comment]
@bonustrack should be ready for review

**Comment by bonustrack** [comment]
This is in standby we should use the merkle tree whitelist strategy for both EVM and Starknet, but the voting strategy on EVM is not deployed yet it's here: https://github.com/snapshot-labs/sx-evm/pull/241 .

**Comment by Sekhmet** [comment]
@bonustrack can we proceed with this PR anyway? I need those changes to implement strategies editing (and if we keep this PR open as a base it will delay it until we are can get whitelist deployed, implemented on sx.js, released etc.)
If we don't want current sx-evm whitelist we can just remove it from possible editor strategies.

**Comment by bonustrack** [comment]
Ok sure

**Review by bonustrack — APPROVED** [review]
utACK, would be nice to just disable EVM whitelist for now (the one without merkle tree)

**Pull request merged**
