### PR TITLE
feat(starknet): add OZ Votes storage proof strategy support

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Closes: https://github.com/snapshot-labs/pitches/issues/74

### How to test

1. Get some token and delegate it to yourself: https://sepolia.etherscan.io/address/0x6fd821e79cdf212ad8b06c59b28fe8c2185291d4#readContract
2. Create new space (with EthSig/EthTx) using OZ Votes storage proof strategy (use above token, slot index 8).
3. Create new proposal.
4. Wait for it to be processed on Herodotus.
5. You can now see your voting power and vote (http://localhost:8080/#/sn-sep:0x07101663a830e0c821785f7537f570901d2a8bf1ed46f70aaacd73c4c7192cf8/proposal/1)

### CODE REVIEW

**Comment by bonustrack** [comment]
I'm not able to create a space, it fail on "StarknetTx.predictSpaceAddress", any idea what's wrong?

image

**Comment by bonustrack** [comment]
Also when I try to edit settings of an existing space, the OZ Votes strategy appear on Proposal validation section instead of the Voting strategies section.
image

**Comment by Sekhmet** [comment]
> I'm not able to create a space, it fail on "StarknetTx.predictSpaceAddress", any idea what's wrong?

Are you still hitting this issue? The only thing I can see is that for some reason lock's `useInstance` would return undefined as `auth.web3` which would mean that it somehow got out of sync with `useWeb3`.

**Comment by bonustrack** [comment]
> > I'm not able to create a space, it fail on "StarknetTx.predictSpaceAddress", any idea what's wrong?
> 
> Are you still hitting this issue? The only thing I can see is that for some reason lock's `useInstance` would return undefined as `auth.web3` which would mean that it somehow got out of sync with `useWeb3`.

Works now

**Comment by bonustrack** [comment]
Ok now I'm stuck with proposal creation, I'm using whitelist and EthSig with `0xeF8305E140ac520225DAf050e2f71d5fBcC543e7` on this space http://localhost:8080/#/sn-sep:0x07032bc36622205a87bbfd6faeff339709ae6c214ff7010f49962b8d41b1f0b2/create/6hxc3j
image

**Comment by Sekhmet** [comment]
@bonustrack sepolia account actually had no balance left. I bridged 1 ETH to it so it should work now.

**Comment by bonustrack** [comment]
My bad I was looking at Ethereum Sepolia instead of SN Sepolia

**Review by bonustrack — APPROVED** [review]
tACK, it take some time to see voting power, but otherwise works well!

**Pull request merged**
