### PR TITLE
feat: add Snapshot Hub integration as ready only platform

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Closes: https://github.com/snapshot-labs/pitches/issues/52

### How to test

1. Go to http://localhost:8080/#/s:arbitrumfoundation.eth
2. It loads.
3. Results are visible for basic voting proposals.
4. Check results for non-basic voting proposal: http://localhost:8080/#/s:arbitrumfoundation.eth/proposal/0xf22530295daee96dffd7f70854475c06216a4d3594929672f71c12bf638bb0c8
5. Check results for basic voting proposal: http://localhost:8080/#/s:arbitrumfoundation.eth/proposal/0x76ff3c3e1750cfbe34dd62ed22c0c126168963d6acce2217acc4bcc7e9e623b7

### Screenshots

image
image
image

### CODE REVIEW

**Comment by bonustrack** [comment]
Some more suggestions:

- Add more markdown syntax, I can see some proposal broken, here with quote or table:
http://localhost:8080/#/s:aave.eth/proposal/0x461571b38365b12ebe39b80d4d9663daa9c7e574cd4bf190ec6fb48dec96371f
http://localhost:8080/#/s:ens.eth/proposal/0x0a7bec3cd182dadbd043e77cf7a610a6e33c5228fabe407cb89c632b578b83a9

- Use abbreviation for numbers like 11m, 387k instead of long numbers, ideally there should be max 3 numbers
Image

- Percentage is off on proposal page in "Results" section for non basic proposal type, showing 40%

**Comment by bonustrack** [comment]
We should have abbreviation for voting power on proposal votes page too:
image
http://localhost:8080/#/s:arbitrumfoundation.eth/proposal/0x22244ef5a988b9231ad073d9fd87cd74f245895f1c0fb82fae52e6ff56cf81d7/votes

**Comment by bonustrack** [comment]
If you want show voting power on proposal page you can use this GQL operation: https://hub.snapshot.org/graphql?query=query%20%7B%0A%20%20vp%20(space%3A%20%22fabien.eth%22%2C%20voter%3A%20%220xeF8305E140ac520225DAf050e2f71d5fBcC543e7%22)%20%7B%0A%20%20%20%20vp%0A%20%20%20%20vp_by_strategy%0A%20%20%7D%0A%7D

**Comment by bonustrack** [comment]
The colored background should appear under the text, currently it change color of the text cuz appear over it
image

**Comment by bonustrack** [comment]
Others things I've noticed:
- Pending proposals show NaN% in results https://bafybeib4lb5gsj7ej3n6bbdnkb2v5lqf4u6n6ectqplcmosqxss3s7zp6q.on.fleek.co/#/s:balancer.eth/proposal/0x9e0a4c87103d9858a9e3662993cd864a161b9a259b5a64894194cf9b3cd4e48b
- We should show 0% instead of 0.00% in results (we can keep decimals but only if its not zero) https://bafybeib4lb5gsj7ej3n6bbdnkb2v5lqf4u6n6ectqplcmosqxss3s7zp6q.on.fleek.co/#/s:aave.eth/proposal/0x80493cdca3b1893e198802cd245e6e3c00f5fcd0b37c09aa41765b17419a71fe

**Comment by Sekhmet** [comment]
@bonustrack cannot reproduce the issue with pending proposals. The one you linked has already started.
There is different pending one, but it displays properly (not showing results):
http://localhost:8080/#/s:aave.eth/proposal/0x0851676384aa4adc836ac6d4f001d1ec7683d5142380a2499bc5ac8b56bb8593

**Comment by bonustrack** [comment]
Ok I can't reproduce too, maybe it was not related to the pending state

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
