### PR TITLE
feat: add EVM network support

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

Closes: https://github.com/snapshot-labs/sx-ui/issues/381

- Allow multiple networks running at the same time (no more `currentNetwork`).
- Support pending transactions on multiple networks.
- Implement EditSpace (EVM only).
- Show actually space description.
- Improvements to pending transactions (only shows when txId is available).
- Separate `USER_VOTES_QUERY` as TheGraph uses AND for WHERE with empty variables.
- Make `waitForTransaction` on Starknet ignore PENDING transactions.

## Test plan

Everything should work :open_mouth:

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
Works well for me, tACK

**Comment by bonustrack** [comment]
@Sekhmet deployment failing on Fleek with
```
9:32:11 PM 01/31/2023: error ipfs-http-client@60.0.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.21.2"
```

**Comment by Sekhmet** [comment]
@bonustrack we need to make it use `node:16` docker image on fleek if possible.

**Comment by bonustrack** [comment]
Works thanks

**Pull request merged**
