### PR TITLE
fix: Use auto-imports to resolve Icons outside of template

### PR DESCRIPTION
**Pull request by samuveth**
This isn't as elegant as I initially hoped, and we might want to consider this instead https://www.npmjs.com/package/@iconify/tailwind?activeTab=readme

Do you think it is stable enough for us to use it @Sekhmet?

### CODE REVIEW

**Comment by Sekhmet** [comment]
> This isn't as elegant as I initially hoped

What exactly isn't elegant in this approach?

Personally coming from non-Vue background I'm not big fan of making everything autoimported (at least until IDE support is improved) as it feels a bit magical and sometimes results in weird conflicts, but I understand it's Vue-way. To me it seems as elegant as autoimports tend to be. You mean that Tailwind style-based icons would be more elegant?

**Comment by samuveth** [comment]
Yeah, I think the auto imports have their limitations, and this is pushing it.

The mismatch in casing and syntax between auto imports and iconify names annoys me. It also feels like a lot to type out. 

With the tailwind based approach, I think we could have a component like this to make it more readable.

Icon.vue
```html
<span :class="`icon-[${name}]`" />
```

And use it like this
```html
<Icon name="mdi-light-home" />
```

**Comment by Sekhmet** [comment]
> With the tailwind based approach, I think we could have a component like this to make it more readable.

Would it work? Generally TailwindCSS only adds classes for styles that you use statically (at least in a sense that transiler can figure out what is used). With string interpolation it might not work (at least it doesn't for regular styles), and opting-in into all icons might be wasteful.

**Comment by samuveth** [comment]
Oh right, probably wouldn't work.

**Comment by samuveth** [comment]
Closing this because importing seems more straight forward and readable.

I also tried `@iconify/tailwind` package which didn't work at all.

**Comment by samuveth** [comment]
@Sekhmet is that comment still relevant now, or can I remove it?

```
// TODO: need to import all icons https://github.com/antfu/unplugin-icons/issues/5
// move to this when stable to avoid imports https://www.npmjs.com/package/@iconify/tailwind
```

**Comment by Sekhmet** [comment]
@samuveth not sure as it was suggested by John, I don't think so, but I'm biased because I l'm okay with explicit imports :D You can remove it if you want.

**Pull request closed without merging**
