### PR TITLE
fix: Hero light mode

### PR DESCRIPTION
**Pull request by samwhosung**
### Summary

The hero on the Homepage was not working on light mode, might have been caused by switching to the `.dark` class for the css variables in https://github.com/snapshot-labs/sx-ui/commit/cbcc39fe6446f23ef5eb09490995af59e8dcbeb6

### CODE REVIEW

**Review by Sekhmet — CHANGES_REQUESTED** [review]
This was regression in https://github.com/snapshot-labs/sx-ui/pull/858 as since this PR there is no longer `light` class (just default style + additional `dark` class. There are no other usages of light, so I think it makes sense to default to light styles and on-demand update styles when `dark` is set (that's what we do with `:root` styles and `dark` class.

I think we could just fix it by this change (on top of master):
```diff
diff --git a/src/style.scss b/src/style.scss
index 78a5824..516bd1f 100644
--- a/src/style.scss
+++ b/src/style.scss
@@ -176,16 +176,13 @@ a,
 .hero {
   background-repeat: repeat;
   background-position: top center;
+  background-image: url('@/assets/grid-light.svg');
 }
 
 .dark .hero {
   background-image: url('@/assets/grid-dark.svg');
 }
 
-.light .hero {
-  background-image: url('@/assets/grid-light.svg');
-}
-
 .no-scrollbar::-webkit-scrollbar {
   display: none;
 }
```

And no longer use `light` class.

**Comment by samuveth** [comment]
Yeah I see. Any reason to change it back otherwise I would leave it how I did now

**Comment by Sekhmet** [comment]
@samuveth Personally I'd revert it, because it's spreads dark handling into more and more places (it's now being handled by `dark` class (all we should need), but this adds `dark:` prefix, extra classes in tailscale config just for background - a bit too much).

`dark` class (and CSS variables controlled by it) should be primary mean of adjusting styles (`dark:` usage in Alert should be migrated at some point too if we have design system variables for those).

**Comment by samuveth** [comment]
Done

**Review by Sekhmet — APPROVED** [review]
tACK

**Pull request merged**
