### PR TITLE
feat: add strategies editing

### PR DESCRIPTION
**Pull request by Sekhmet**
Closes: https://github.com/snapshot-labs/sx-ui/issues/659

This PR adds ability to edit authenticators/votingStrategies/proposalValidationStrategy on spaces (EVM and Starknet).

## Test plan
- Deploy new space (to make sure it has all metadata created properly, old spaces didn't have proposal validation strategies metadata).
- Try editing it.

## Screenshots

Temporary UI, but functional.

image

### CODE REVIEW

**Comment by bonustrack** [comment]
@Sekhmet Can you fix conflicts? Currently I can't run the code locally, it give me this error:
```
Error: Cannot find module '@esbuild-plugins/node-globals-polyfill'
```

**Comment by samuveth** [comment]
Any idea why there is no preview deployment again?

**Comment by Sekhmet** [comment]
@samuveth neither https://github.com/snapshot-labs/sx-ui/pull/807 has deployment 🤔

**Comment by bonustrack** [comment]
The edit settings page doesn't load for spaces on EVM chains, I got this error message:
image

Otherwise it works well for me for Starknet space. I would recommend to remove "Edit settings" item from the menu for now, I'd like to improve the design and most likely merge it within the settings page before making it available to the public.

**Comment by Sekhmet** [comment]
> The edit settings page doesn't load for spaces on EVM chains for me, I got this error message

It won't work for old spaces, because for those we didn't store metadata for all strategies so editor doesn't know how to restore the state. If you create new space on this branch and it still doesn't work let me know and I will check it out, because that shouldn't be the case.

**Comment by bonustrack** [comment]
I tried to create a space but Goerli subgraph indexing is failing with this error:
image

**Comment by Sekhmet** [comment]
@bonustrack thanks, it was a small fix on subgraph, already deployed everywhere, it will probably take a long time to sync up 😢 

https://github.com/snapshot-labs/sx-subgraph/pull/42

**Comment by bonustrack** [comment]
There is still an issue with metadata, got this error triggered from `constants.ts`:
```
   parseParams: async (params: string, metadata: StrategyParsedMetadata | null) => {
      if (!metadata) throw new Error('Missing metadata');
```

**Review by bonustrack — APPROVED** [review]
I was looking at a wrong space, it actually works well on both EVM and Starknet spaces, tACK

**Pull request merged**
