### PR TITLE
feat: index multiple delegations

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

**Only Starknet was tested as of now.**

Closes: https://github.com/snapshot-labs/sx-ui/issues/833

Depends on https://github.com/snapshot-labs/sx-api/pull/205
Depends on https://github.com/snapshot-labs/sx-subgraph/pull/43

### How to test

1. Run local sx-api.
2. Run sx-ui with sn-tn only: `VITE_ENABLED_NETWORKS=sn-tn yarn dev`.
3. Deploy new space with multiple delegations.
4. Edit that space delegations in edit space modal.
5. View delegations for space (**currently subgraph fails for some subgraphs because it's overloaded**).

### Screenshots

image
image
image

### CODE REVIEW

**Comment by bonustrack** [comment]
Works well, some suggestions for the style:

- Use full rounded button for "Add new delegation API"
- Rename this button to "Add delegation" (on the modal title too)

Nice to have:

- Ideally we should not have a modal on top of a modal, this makes modal backdrop twice darker. I imagine if we figure out this it will be easier to reuse others modals like select token list modal without duplicate code.

**Comment by Sekhmet** [comment]
> Ideally we should not have a modal on top of a modal, this makes modal backdrop twice darker. I imagine if we figure out this it will be easier to reuse others modals like select token list modal without duplicate code.

Do you want to just avoid second backdrop or make it more complex (like system where you open multiple modals at once, but only one is visible at the time etc.)? If it's latter I'd create separate issue for it.

**Comment by bonustrack** [comment]
I mean the later

**Comment by Sekhmet** [comment]
Looks like all subgraphs were updated other than arbitrum which is stuck (?).
I will hardcode it to specific version so all APIs have same format and this can be merged (because subgraphs have changed master deployment is now broken).

We should come back to see if it's unstuck later on and update it back to latest.

**Pull request merged**
