### PR TITLE
chore: Add color variables from Figma and refactor

### PR DESCRIPTION
**Pull request by samwhosung**
### Summary

Add color variables from the design system on Figma.

Also fixes a small bug where the disabled button text color wasn't the correct one because of missing `rgb()`.

This PR mostly adds the color variables, we will start using them all in future PRs

### How to test

1. Open two tabs with both versions to compare and click through the UI

### CODE REVIEW

**Comment by Sekhmet** [comment]
@samuveth can you link to Figma?

**Comment by samuveth** [comment]
https://www.figma.com/file/TnYkSDoOvjaxbRpwSfXGhO/%23library?node-id=72%3A2774&mode=dev

**Comment by Sekhmet** [comment]
@samuveth I think we will have some changes to the naming (positive to success) etc. Do you think this should wait?

**Comment by samuveth** [comment]
Yes, I will make those changes

**Comment by samuveth** [comment]
Done

**Review by Sekhmet — APPROVED** [review]
tACK

**Pull request merged**
