### PR TITLE
feat: add strategies descriptions

### PR DESCRIPTION
**Pull request by bonustrack**
Display for strategies descriptions on space creation
image

### CODE REVIEW

**Review by Sekhmet — COMMENTED** [review]
image

Do you think it would look better centered like this? It looks a bit off with icon on top I think.

@bonustrack CI is failing and it needs a rebase. I can handle it if you want.

**Comment by bonustrack** [comment]
@Sekhmet Centered looks good too feel free to take over this PR. I think also we should enforce a certain height for the card with truncate of text so it doesnt look bad on mobile

**Review by Sekhmet — APPROVED** [review]
tACK

**Comment by Sekhmet** [comment]
Added real descriptions for strategies from https://docs.snapshotx.xyz/protocol-sx-evm/authenticators

**Pull request merged**
