### PR TITLE
feat: add v0.5.0 compatibility

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

This PR adds v0.5.0 contracts compatibility.

Closes: https://github.com/snapshot-labs/sx-ui/issues/650
Closes: https://github.com/snapshot-labs/sx-ui/issues/608

Depends on: https://github.com/snapshot-labs/sx.js/pull/193

## Test plan

- Link sx.js from PR above to sx-ui (run with `yarn dev --force`) **and mana - you need local mana with sx.js even though there are no changes on mana**.
- Use local mana.
- Create space, propose, vote.

### CODE REVIEW

**Comment by bonustrack** [comment]
I can't create a space, for some reason it stop after execution deployment. deploying a space contract never got trigger on MetaMask. I used Timelock execution strategy to test.

**Comment by Sekhmet** [comment]
@bonustrack Graph's IPFS node is down.

**Comment by bonustrack** [comment]
I'll wait TheGraph to be back then

**Comment by bonustrack** [comment]
This doesnt require local Mana anymore right? When I try to create a proposal I got this error: 
image
On this space: http://localhost:8080/#/gor:0x7303c2f08f1da0b5f8e0ebdc060c58a50a207468

**Comment by Sekhmet** [comment]
@bonustrack sorry, it does, there are no changes on mana, but you have to have latest sx.js from master on it: https://github.com/snapshot-labs/sx.js/pull/195

Didn't submit PR to mana because this bump PR wasn't merged.

**Review by bonustrack — APPROVED** [review]
Works well now, tACK

**Pull request merged**
