### PR TITLE
fix: make Starknet whitelist work again

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Fixes two issues:
- Make merkle tree address lookup independent of paddings.
- Use validation strategy strategies metadata when proposing (it was fixed in PR that adds support for editing strategies, but never ported back to master).

### Test plan

- Create space with merkle whitelist strategy as validation strategy but not as voting strategy.
- Try proposing.

### CODE REVIEW

**Comment by bonustrack** [comment]
Others things I've noticed:
- Pending proposals show NaN% in results https://bafybeib4lb5gsj7ej3n6bbdnkb2v5lqf4u6n6ectqplcmosqxss3s7zp6q.on.fleek.co/#/s:balancer.eth/proposal/0x9e0a4c87103d9858a9e3662993cd864a161b9a259b5a64894194cf9b3cd4e48b
- We should show 0% instead of 0.00% in results (we can keep decimals but only if its not zero) https://bafybeib4lb5gsj7ej3n6bbdnkb2v5lqf4u6n6ectqplcmosqxss3s7zp6q.on.fleek.co/#/s:aave.eth/proposal/0x80493cdca3b1893e198802cd245e6e3c00f5fcd0b37c09aa41765b17419a71fe

**Comment by bonustrack** [comment]
Works well when propose with ETH and SN wallet, vote with SN wallet, but vote with ETH wallet give me this error "Incorrect address type", that vote use whitelist as voting power

**Comment by bonustrack** [comment]
I can cast vote now, somehow my votes doesn't get indexed, here is a tx for my latest vote:
https://testnet.starkscan.co/tx/0x15069706d2492c4a0a062c154d430f2d75cee2709259ab72ea398769ce38556
For this proposal:
http://localhost:8080/#/sn-tn:0x03d405156f55f2896898ac44ac91939c40711e5da5df193dfdc5985a33d6d8ac/proposal/1
Using address 0xeF8305E140ac520225DAf050e2f71d5fBcC543e7

**Comment by Sekhmet** [comment]
@bonustrack looks like sx-api is stuck on some proposal, debugging it now.

**Review by bonustrack — APPROVED** [review]
Approving this since its not related tACK

**Pull request merged**
